spring.application.name=record-api
server.port=8080

spring.datasource.url=jdbc:h2:mem:recorddb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

api.auth.token=demo-secret-token

spring.jackson.property-naming-strategy=UPPER_CAMEL_CASE
